(venv) root@vm-b3dba883-74:~/M-S-A# pip install flask>=2.2.0 werkzeug>=2.2.0
(venv) root@vm-b3dba883-74:~/M-S-A# pip install flask>=2.2.0 werkzeug>=2.2.0
(venv) root@vm-b3dba883-74:~/M-S-A# python main.py
2025-03-16 04:01:03,815 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-16 04:01:03,818 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-16 04:01:03,819 - apscheduler.scheduler - INFO - Added job "scheduled_scrape" to job store "default"
2025-03-16 04:01:03,819 - apscheduler.scheduler - INFO - Added job "<lambda>" to job store "default"
2025-03-16 04:01:03,819 - apscheduler.scheduler - INFO - Scheduler started
サーバー起動時刻（JST）: 2025-03-16 04:01:03 JST+0900
アプリケーションを起動しています: http://0.0.0.0:5000
初期データがありません。スクレイピングを実行します...
2025-03-16 04:01:03,833 - __main__ - INFO - 定期スクレイピングを開始します
2025-03-16 04:01:03,841 - __main__ - INFO - スクレイピング開始: 対象店舗数 802
2025-03-16 04:01:03,842 - app - INFO - スクレイピングを開始します（店舗数: 802、並列実行数: 14）
2025-03-16 04:01:04,250 - pyppeteer.launcher - INFO - Browser listening on: ws://127.0.0.1:47953/devtools/browser/c079c5c8-aa46-4b96-a0ee-d89220f2589a
2025-03-16 04:01:04,280 - app - INFO - バッチ処理中: 1〜14店舗 / 合計802店舗
2025-03-16 04:01:04,739 - app - INFO - スクレイピング開始: https://www.cityheaven.net/chiba/A1202/A120201/wonder-hole/attend/soon/
2025-03-16 04:01:04,740 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1303/A130301/eos-gal/attend/soon/
2025-03-16 04:01:04,741 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1305/A130505/stella_tokyo/attend/soon/
2025-03-16 04:01:04,741 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1312/A131205/kanteidan2/attend/soon/
2025-03-16 04:01:04,742 - app - INFO - スクレイピング開始: https://www.cityheaven.net/saitama/A1103/A110303/parfaiteluna/attend/soon/
2025-03-16 04:01:04,742 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1304/A130401/deli-shinjuku-k/attend/soon/
2025-03-16 04:01:04,743 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1305/A130505/finemotion/attend/soon/
2025-03-16 04:01:04,744 - app - INFO - スクレイピング開始: https://www.cityheaven.net/chiba/A1202/A120201/aneshinchi/attend/soon/
2025-03-16 04:01:04,744 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1304/A130401/ug-platinum/attend/soon/
2025-03-16 04:01:04,745 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1304/A130401/gingira/attend/soon/
2025-03-16 04:01:04,745 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1313/A131301/delice-love/attend/soon/
2025-03-16 04:01:04,746 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1304/A130401/shinjuku-deri/attend/soon/
2025-03-16 04:01:04,754 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1304/A130401/tia/attend/soon/
2025-03-16 04:01:04,768 - app - INFO - スクレイピング開始: https://www.cityheaven.net/tokyo/A1304/A130401/ultragrace/attend/soon/
2025-03-16 04:01:09,458 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.detachFromTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.detachFromTarget): No session with given id
2025-03-16 04:01:11,884 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.detachFromTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.detachFromTarget): No session with given id
2025-03-16 04:01:12,345 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.detachFromTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.detachFromTarget): No session with given id
2025-03-16 04:01:12,676 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.detachFromTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.detachFromTarget): No session with given id
シフト件数: 11
2025-03-16 04:01:13,670 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.detachFromTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.detachFromTarget): No session with given id
^Z
[2]+  Stopped                 python main.py
(venv) root@vm-b3dba883-74:~/M-S-A#